#baseurl         = "https://elated-torvalds-264633.netlify.com/"
baseUrl         = "https://blog.marcelocavalcante.net/"
theme           = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = "marcelocavalcante"
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Marcelo Cavalcante Rocha"
  #subtitle    = "Because Automation is Fun"

  cover       = "defimg/kalibbw.jpg"
  description = "Marcelo Cavalcante Rocha - Blog Pessoal"
  metaDescription = "Marcelo Cavalcante Rocha - Kalib. Devops, Linux, Automação e Programação"
  googleAnalytics = "UA-42903485-2"
  customCSS = []
  RSSLink = ""

  twitterName = "MarceloKalib"
  fbName = "marcelocavalcanter"
  githubName = "kalib"
  linkedinName = "marcelocrocha"
  instagramName = "marcelocavalcanterocha"

  logo = "/logo/logo-edited-branca-3.png"
  #logo = "hugo-logo.png"
  logo2 = "/logo/bash.png"
  orgName = "Marcelo Cavalcante"
  orgWebsite = "https://blog.marcelocavalcante.net"
  orgDescription = "Marcelo Cavalcante - Automation is fun..."

  author = "Marcelo Cavalcante"
  authorAvatar = "img/kalib_picture_pq_circle_pq.png"
  authorLocation = "Toronto, ON"
  authorWebsite = "https://blog.marcelocavalcante.net"
  authorDescription = "DevOps Engineer"

  pageNotFoundTitle = "Ops.. página não encontrada."

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  identifier = "Home"
  name = "Home"
  url = "/post"
  weight = 200

#[[menu.main]]
#  name = "Quem sou"
#  url = "about.md"
#  weight = 100

#[[menu.main]]
#  name = "|"
#  url = "/tags/Devops/"
#  weight = 100
#
#[[menu.main]]
#  name = "Devops"
#  url = "/tags/devops/"
#  weight = 99

#[[menu.main]]
#  name = "Linux"
#  url = "/tags/linux/"
#  weight = 99

#[[menu.main]]
#  name = "Devops"
#  url = "/categories/devops/"
#  weight = 99

#[[menu.main]]
#  name = "External"
#  url = "https://google.com/"
#  weight = 95
